### ISSUE TITLE
Master Transcription Slots Availability Bug

### ISSUE THREAD

**Issue by theinternetftw** [theinternetftw/xkcd2601#2]
Full runtime: [09:07:12]

Slots can be claimed in increments of 10 minutes. You can claim a single slot, or a bigger slot that is e.g. 30 minutes if you like.

Title of a slot claim bug should look like e.g. **Claiming [00:10:00] to [00:20:00]**

All slots complete!

**Comment by edegeltje** [comment]
my file seems to be only 8:41:08 long??? are there multiple versions???

EDIT: downloading the file seems to have somehow applied magic dust to my file, somehow shortening it. guess ill have to re-transcribe my stuff, till i find what i ACTUALLY transcribed. and re-write the timestamps

**Comment by theinternetftw** [comment]
@edegeltje see discussion here #23 , that length seems to match the "it's the player's fault" diagnosis.

**Comment by theinternetftw** [comment]
All slots complete! Bug done!
