### ISSUE TITLE
Is the mp3 file always the same? (update - signs currently point to 'yes')

### ISSUE THREAD

**Issue by theinternetftw** [theinternetftw/xkcd2601#23]
I had a contributor mention that they didn't find one of the fun fact interjections in their version of the audio. They messed around and said that maybe when you play the audio in-browser, it sends a different file versus when you download it.

I'd like to find out if there really are different versions of the file.

The SHA1 of the https://xkcd.com/2601/radio.mp3 I have is fb2292dd1e021ae01b949ef2673f6be00e496e49

Anyone else have different?

**Comment by mrphlip** [comment]
My file matches yours. And it seems to be the same whether I access it within the page, or download it with wget.

**Comment by benediktwerner** [comment]
I also get the same hash. It's weird though, Windows Explorer and Windows Media Player show its length as 08:41:08. But when listening in the browser, it says 09:07:12. In VLC, it also starts around 8h but then the final length increases as it goes on up to 9h as well.

So it's probably an issue with the playback software. Maybe the file has some weird non-spec or unusual stuff which confuses some software?

**Comment by mrphlip** [comment]
ffmpeg (ffprobe) says the duration is 9:07:12.288
mpv agrees, 9:07:12
vlc gets very confused, and shows a duration that starts at 4:33:36 but rapidly increases as it starts to actually play, and seems to asymptotically approach the correct value? it looks like it's getting very confused by _something_.

**Comment by theinternetftw** [comment]
Think we can close this now.
