### ISSUE TITLE
Transcribers don't currently note their changes from the original audio

### ISSUE THREAD

**Issue by culcube** [theinternetftw/xkcd2601#57]
At the moment the file xkcd.lgo includes comments (and code) from the transcriber at lines 65 through to 74, inclusive, which do not appear in the audio file (line 65 is at approximately 4 minutes and 20 seconds into the audio).

It might be useful to specifically annotate this additional code (including the comments) to make it obvious that this is intentional divergence from the original audio.

**Comment by theinternetftw** [comment]
Addressed in the commit above, hopefully.
