### ISSUE TITLE
full transcription by merging human and machine transcription and fixing some errors

### ISSUE THREAD

**Issue by Gh05t-1337** [theinternetftw/xkcd2601#58]
https://github.com/Gh05t-1337/xkcd2601

![xkcd2601](https://user-images.githubusercontent.com/95411780/161406094-da35747a-cd9b-4814-800e-c8eb752cfb8e.png)

**Comment by julio73** [comment]
Nice work!

**Comment by theinternetftw** [comment]
Looks great. And it's definitely a useful resource for comparing output.

This repo need those missing comments though, as well as timestamps to help verify things (having those has already helped fix some errors that are still in the above image).

**Comment by Gh05t-1337** [comment]
i'll try to add them, so it becomes an even more useful resouce

**Comment by Gh05t-1337** [comment]
added comments and fixes
![xkcd2601](https://user-images.githubusercontent.com/95411780/161407176-2a556077-2b1c-43ff-84f5-a45f7f5e486a.png)

**Comment by theinternetftw** [comment]
Alright, there's enough context here to start pulling stuff in. I'm doing that now manually, as the pull request is doing some weird diff stuff where it deletes a bunch of stuff (maybe because so many changes have been made to it).

Anyway, it's in progress. Thanks!

**Comment by theinternetftw** [comment]
All code has now been fixed up and moved in! Transcription complete with commentary and everything!
